//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public int SprintID { get; set; }
        public int EmployeeID { get; set; }
        public int RoleID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public string TaskDescription { get; set; }
        public int Difficulty { get; set; }
        public Nullable<int> Estimation { get; set; }
        public Nullable<int> TemplateID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Role Role { get; set; }
        public virtual Sprint Sprint { get; set; }
    }
}
