//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceApplicationTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskID { get; set; }
        public Nullable<int> SprintID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Duration { get; set; }
        public string TaskDescription { get; set; }
        public int Difficulty { get; set; }
        public Nullable<int> Estimation { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Role Role { get; set; }
        public virtual Sprint Sprint { get; set; }
    }
}
